services:
  - type: web
    name: peanut-butter-manufacturing
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /(.*)*
        destination: /index.html
